apiVersion: v1
kind: Service
metadata:
  name: service-devops
  labels:
    app: devops-course-2025
    svc: flask-front
spec:
  type: LoadBalancer
  selector:
    app: devops-course-2025
    svc: flask-front
  ports:
  - name: flask-port
    port: 8000
    targetPort: 5000
  externalIPs:
  - 10.0.2.15